FROM ubuntu:xenial

ENV HOME /home/dmarc

WORKDIR /home/dmarc
COPY . .

RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:longsleep/golang-backports && apt-get update && apt-get install -y golang-go git debhelper
RUN dpkg-buildpackage
