FROM golang:1.11 as build
ENV HOME /home/dmarc
ENV GOOS linux
ENV GOARCH amd64
ENV CGO_ENABLED 0
WORKDIR /home/dmarc
COPY . .
RUN make

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=build /home/dmarc/bin/godmarcparser .
EXPOSE 8080
# Use kubernetes to add config.json
CMD ["./godmarcparser"]
